version: "3.5"

services:
  bot_start:
    image: "app-base"
    env_file: ".env"
    network_mode: "host"
    command: "start"
  restart: always

  bot_setup:
    image: "app-base"
    build:
      context: .
      dockerfile: Dockerfile
    command: "setup_db"

  zmongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-dbname}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-changeme}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-Alice_quest}
    restart: always
    logging:
      driver: none
